name:                goodstuff
version:             "0.19"
github:              "chameco/goodstuff"
license:             GPL-3
author:              "Samuel Breese"
maintainer:          "samuel@chame.co"
copyright:           "2018 Samuel Breese"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/chameco/goodstuff#readme>

ghc-options:
- -Wall
- -Werror
- -threaded
- -rtsopts
- -with-rtsopts=-N

dependencies:
- base
- classy-prelude
- text
- bytestring
- case-insensitive
- mtl
- exceptions
- safe-exceptions
- string-conv
- directory
- filepath
- temporary
- uuid
- optparse-applicative
- pcre-heavy
- parsec
- process
- process-extras
- ansi-terminal
- random
- pretty-simple
- warp
- http-types
- http-client
- http-client-tls
- wai
- wai-extra
- wai-cors
- wai-websockets
- websockets
- scotty
- cookie
- aeson
- tagsoup
- blaze-html
- clay
- jmacro
- sqlite-simple
- postgresql-simple
- pureMD5
- cryptonite
- base64-bytestring

default-extensions:
- NoImplicitPrelude
- TupleSections
- LambdaCase
- MultiWayIf
- TypeOperators
- OverloadedStrings
- OverloadedLists
- ViewPatterns
- PatternSynonyms
- ExplicitForAll
- TypeApplications
- ScopedTypeVariables
- RankNTypes
- LiberalTypeSynonyms
- NamedFieldPuns
- RecordWildCards
- FlexibleInstances
- FlexibleContexts
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- GeneralizedNewtypeDeriving
- InstanceSigs
- ConstrainedClassMethods
- MultiParamTypeClasses
- FunctionalDependencies
- DeriveGeneric
- NamedWildCards
- PartialTypeSignatures
- ExistentialQuantification
- GADTSyntax
- GADTs
- TypeFamilies
- TypeFamilyDependencies
- AllowAmbiguousTypes
- KindSignatures
- ConstraintKinds
- DataKinds
- PolyKinds
- TypeInType
- EmptyCase
- StandaloneDeriving
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- DuplicateRecordFields
- OverloadedLabels
- BangPatterns
- ApplicativeDo
- NegativeLiterals
- NumDecimals
- BinaryLiterals
- QuasiQuotes
- UnicodeSyntax
- NoMonomorphismRestriction
- PostfixOperators
- PackageImports

executables:
  goodstuff:
    main:                Main.hs
    source-dirs:         backend