name:                goodstuff
version:             "0.4"
github:              "chameco/goodstuff"
license:             GPL-3
author:              "Samuel Breese"
maintainer:          "samuel@chame.co"
copyright:           "2018 Samuel Breese"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/chameco/goodstuff#readme>

ghc-options:
- -Wall
- -Werror
- -optl-static
- -optl-pthread

dependencies:
- base
- classy-prelude
- text
- mtl
- exceptions
- string-conv
- directory
- filepath
- temporary
- pcre-heavy
- process
- process-extras
- ansi-terminal
- pretty-simple
- wai
- wai-cors
- scotty
- aeson
- http-types
- http-client
- http-client-tls
- tagsoup

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- TupleSections
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- BangPatterns
- KindSignatures
- TypeOperators
- ScopedTypeVariables
- TypeApplications
- ConstraintKinds
- RankNTypes
- FunctionalDependencies
- GADTs
- DataKinds
- TypeFamilies
- TypeFamilyDependencies

library:
  source-dirs: src

executables:
  goodstuff:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - goodstuff