module Coal.Snapshot.IotM where

import Coal.Snapshot.Utility (enumerate, splitEvery)
import Data.Foldable (fold)
import Data.Function (const, ($))
import Data.Functor (map, (<$>))
import Data.Ring (negate)
import Data.Semigroup ((<>))
import Data.Sequence (Seq, singleton, splitAt)
import Data.Tuple (Tuple(..))
import Data.Unfoldable (replicate)

buildIotM :: Seq Boolean -> String
buildIotM iotm = fold [ "<table>"
                      , fold $ map (\(Tuple y ms) -> buildYear y ms) labeled
                      , "</table>"
                      ]
  where (Tuple firstYear otherYears) = splitAt 3 iotm
        labeled :: Seq (Tuple Int (Seq (Tuple Int Boolean)))
        labeled =  singleton (Tuple 2004 $ replicate 9 (Tuple (-1) false) <> enumerate 10 firstYear) <> enumerate 2005 (enumerate 1 <$> splitEvery 12 otherYears)

buildYear :: Int -> Seq (Tuple Int Boolean) -> String
buildYear y ms = fold [ "<tr>"
                      , fold $ map (\(Tuple m b) -> buildMonth y m b) ms
                      , "</tr>"
                      ]

monthHelper :: String -> String -> Boolean -> String
monthHelper name wiki b = fold [ "<td class=\"", if b then "greenbox" else "whitebox", "\">"
                               , "<a href=\"", wiki, "\"><div class=\"iotmname\">", name, "</div></a>"
                               , "</td>"
                               ]

buildMonth :: Int -> Int -> Boolean -> String
buildMonth 2004 10 = monthHelper "Dark Jill-O-Lantern" "http://kol.coldfront.net/thekolwiki/index.php/Dark_Jill-O-Lantern"
buildMonth 2004 11 = monthHelper "hand turkey outline" "http://kol.coldfront.net/thekolwiki/index.php/Hand_turkey_outline"
buildMonth 2004 12 = monthHelper "crimbo elfling" "http://kol.coldfront.net/thekolwiki/index.php/Crimbo_elfling"
buildMonth 2005  1 = monthHelper "orphan baby yeti" "http://kol.coldfront.net/thekolwiki/index.php/Orphan_baby_yeti"
buildMonth 2005  2 = monthHelper "silk garter snake" "http://kol.coldfront.net/thekolwiki/index.php/Silk_garter_snake"
buildMonth 2005  3 = monthHelper "lucky Tam O'Shanter" "http://kol.coldfront.net/thekolwiki/index.php/Lucky_Tam_O%27Shanter"
buildMonth 2005  4 = monthHelper "personal raindrop" "http://kol.coldfront.net/thekolwiki/index.php/Personal_raindrop"
buildMonth 2005  5 = monthHelper "miniature gravy-covered maypole" "http://kol.coldfront.net/thekolwiki/index.php/Miniature_gravy-covered_maypole"
buildMonth 2005  6 = monthHelper "deflated inflatable dodecapede" "http://kol.coldfront.net/thekolwiki/index.php/Deflated_inflatable_dodecapede"
buildMonth 2005  7 = monthHelper "wax lips" "http://kol.coldfront.net/thekolwiki/index.php/Wax_lips"
buildMonth 2005  8 = monthHelper "pygmy bugbear shaman" "http://kol.coldfront.net/thekolwiki/index.php/Pygmy_bugbear_shaman"
buildMonth 2005  9 = monthHelper "Jekyllin hide belt" "http://kol.coldfront.net/thekolwiki/index.php/Jekyllin_hide_belt"
buildMonth 2005 10 = monthHelper "doppelshifter egg" "http://kol.coldfront.net/thekolwiki/index.php/Doppelshifter_egg"
buildMonth 2005 11 = monthHelper "miniscule temporal rip" "http://kol.coldfront.net/thekolwiki/index.php/Miniscule_temporal_rip"
buildMonth 2005 12 = monthHelper "sweet nutcracker" "http://kol.coldfront.net/thekolwiki/index.php/Sweet_nutcracker"
buildMonth 2006  1 = monthHelper "Tome of Snowcone Summoning" "http://kol.coldfront.net/thekolwiki/index.php/Tome_of_Snowcone_Summoning"
buildMonth 2006  2 = monthHelper "iceberglet" "http://kol.coldfront.net/thekolwiki/index.php/Iceberglet"
buildMonth 2006  3 = monthHelper "March hat" "http://kol.coldfront.net/thekolwiki/index.php/March_hat"
buildMonth 2006  4 = monthHelper "McPhee's Grimoire of Hilarious Object Summoning" "http://kol.coldfront.net/thekolwiki/index.php/McPhee%27s_Grimoire_of_Hilarious_Object_Summoning"
buildMonth 2006  5 = monthHelper "homeless hobo spirit" "http://kol.coldfront.net/thekolwiki/index.php/Homeless_hobo_spirit"
buildMonth 2006  6 = monthHelper "astral badger" "http://kol.coldfront.net/thekolwiki/index.php/Astral_badger"
buildMonth 2006  7 = monthHelper "jewel-eyed wizard hat" "http://kol.coldfront.net/thekolwiki/index.php/Jewel-eyed_wizard_hat"
buildMonth 2006  8 = monthHelper "Comma Chameleon egg" "http://kol.coldfront.net/thekolwiki/index.php/Comma_Chameleon_egg"
buildMonth 2006  9 = monthHelper "Travoltan trousers" "http://kol.coldfront.net/thekolwiki/index.php/Travoltan_trousers"
buildMonth 2006 10 = monthHelper "plastic pumpkin bucket" "http://kol.coldfront.net/thekolwiki/index.php/Plastic_pumpkin_bucket"
buildMonth 2006 11 = monthHelper "pilgrim shield" "http://kol.coldfront.net/thekolwiki/index.php/Pilgrim_shield"
buildMonth 2006 12 = monthHelper "yuletide troll chrysalis" "http://kol.coldfront.net/thekolwiki/index.php/Yuletide_troll_chrysalis"
buildMonth 2007  1 = monthHelper "Great Ball of Frozen Fire" "http://kol.coldfront.net/thekolwiki/index.php/Great_Ball_of_Frozen_Fire"
buildMonth 2007  2 = monthHelper "Libram of Candy Heart Summoning" "http://kol.coldfront.net/thekolwiki/index.php/Libram_of_Candy_Heart_Summoning"
buildMonth 2007  3 = monthHelper "dandy lion cub" "http://kol.coldfront.net/thekolwiki/index.php/Dandy_lion_cub"
buildMonth 2007  4 = monthHelper "bad penguin egg" "http://kol.coldfront.net/thekolwiki/index.php/Bad_penguin_egg"
buildMonth 2007  5 = monthHelper "Mayflower bouquet" "http://kol.coldfront.net/thekolwiki/index.php/Mayflower_bouquet"
buildMonth 2007  6 = monthHelper "bottled green pixie" "http://kol.coldfront.net/thekolwiki/index.php/Bottled_green_pixie"
buildMonth 2007  7 = monthHelper "bottle-rocket crossbow" "http://kol.coldfront.net/thekolwiki/index.php/Bottle-rocket_crossbow"
buildMonth 2007  8 = monthHelper "wizard action figure" "http://kol.coldfront.net/thekolwiki/index.php/Wizard_action_figure"
buildMonth 2007  9 = monthHelper "navel ring of navel gazing" "http://kol.coldfront.net/thekolwiki/index.php/Navel_ring_of_navel_gazing"
buildMonth 2007 10 = monthHelper "class five ecto-larva" "http://kol.coldfront.net/thekolwiki/index.php/Class_five_ecto-larva"
buildMonth 2007 11 = monthHelper "V for Vivala mask" "http://kol.coldfront.net/thekolwiki/index.php/V_for_Vivala_mask"
buildMonth 2007 12 = monthHelper "Crimbo P.R.E.S.S.I.E." "http://kol.coldfront.net/thekolwiki/index.php/Crimbo_P._R._E._S._S._I._E._(hatchling)"
buildMonth 2008  1 = monthHelper "Libram of Divine Favors" "http://kol.coldfront.net/thekolwiki/index.php/Libram_of_Divine_Favors"
buildMonth 2008  2 = monthHelper "naughty origami kit" "http://kol.coldfront.net/thekolwiki/index.php/Naughty_origami_kit"
buildMonth 2008  3 = monthHelper "sane hatrack" "http://kol.coldfront.net/thekolwiki/index.php/Sane_hatrack"
buildMonth 2008  4 = monthHelper "Sp'n-Zor's Grimoire of \"Tasteful\" Gifts" "http://kol.coldfront.net/thekolwiki/index.php/Sp%27n-Zor%27s_Grimoire_of_%22Tasteful%22_Gifts"
buildMonth 2008  5 = monthHelper "packet of mayfly bait" "http://kol.coldfront.net/thekolwiki/index.php/Packet_of_mayfly_bait"
buildMonth 2008  6 = monthHelper "llama lama cria" "http://kol.coldfront.net/thekolwiki/index.php/Llama_lama_cria"
buildMonth 2008  7 = monthHelper "little box of fireworks" "http://kol.coldfront.net/thekolwiki/index.php/Little_box_of_fireworks"
buildMonth 2008  8 = monthHelper "cotton candy cocoon" "http://kol.coldfront.net/thekolwiki/index.php/Cotton_candy_cocoon"
buildMonth 2008  9 = monthHelper "haiku katana" "http://kol.coldfront.net/thekolwiki/index.php/Haiku_katana"
buildMonth 2008 10 = monthHelper "spooky rattling cigar box" "http://kol.coldfront.net/thekolwiki/index.php/Spooky_rattling_cigar_box"
buildMonth 2008 11 = monthHelper "Scratch 'n' Sniff Sticker Tome" "http://kol.coldfront.net/thekolwiki/index.php/Scratch_%27n%27_Sniff_Sticker_Tome"
buildMonth 2008 12 = monthHelper "candy cornucopia" "http://kol.coldfront.net/thekolwiki/index.php/Candy_cornucopia"
buildMonth 2009  1 = monthHelper "container of Spooky Putty" "http://kol.coldfront.net/thekolwiki/index.php/Container_of_Spooky_Putty"
buildMonth 2009  2 = monthHelper "Libram of Love Songs" "http://kol.coldfront.net/thekolwiki/index.php/Libram_of_Love_Songs"
buildMonth 2009  3 = monthHelper "Apathargic Bandersnatch" "http://kol.coldfront.net/thekolwiki/index.php/Apathargic_Bandersnatch"
buildMonth 2009  4 = monthHelper "Elvish sunglasses" "http://kol.coldfront.net/thekolwiki/index.php/Elvish_sunglasses"
buildMonth 2009  5 = monthHelper "Clan pool table" "http://kol.coldfront.net/thekolwiki/index.php/Clan_pool_table"
buildMonth 2009  6 = monthHelper "infant sandworm" "http://kol.coldfront.net/thekolwiki/index.php/Infant_sandworm"
buildMonth 2009  7 = monthHelper "Bag o' Tricks" "http://kol.coldfront.net/thekolwiki/index.php/Bag_o%27_Tricks"
buildMonth 2009  8 = monthHelper "floaty stone sphere" "http://kol.coldfront.net/thekolwiki/index.php/Floaty_stone_sphere"
buildMonth 2009  9 = monthHelper "Tome of Sugar Shummoning" "http://kol.coldfront.net/thekolwiki/index.php/Tome_of_Sugar_Shummoning"
buildMonth 2009 10 = monthHelper "squamous polyp" "http://kol.coldfront.net/thekolwiki/index.php/Squamous_polyp"
buildMonth 2009 11 = monthHelper "moveable feast" "http://kol.coldfront.net/thekolwiki/index.php/Moveable_feast"
buildMonth 2009 12 = monthHelper "suspicious stocking" "http://kol.coldfront.net/thekolwiki/index.php/Suspicious_stocking"
buildMonth 2010  1 = monthHelper "stinky cheese ball" "http://kol.coldfront.net/thekolwiki/index.php/Stinky_cheese_ball"
buildMonth 2010  2 = monthHelper "Libram of BRICKOs" "http://kol.coldfront.net/thekolwiki/index.php/Libram_of_BRICKOs"
buildMonth 2010  3 = monthHelper "Clan looking glass" "http://kol.coldfront.net/thekolwiki/index.php/Clan_looking_glass"
buildMonth 2010  4 = monthHelper "panicked kernel" "http://kol.coldfront.net/thekolwiki/index.php/Panicked_kernel"
buildMonth 2010  5 = monthHelper "Crown of Thrones" "http://kol.coldfront.net/thekolwiki/index.php/Crown_of_Thrones"
buildMonth 2010  6 = monthHelper "glowing frisbee" "http://kol.coldfront.net/thekolwiki/index.php/Glowing_frisbee"
buildMonth 2010  7 = monthHelper "Juju Mojo Mask" "http://kol.coldfront.net/thekolwiki/index.php/Juju_Mojo_Mask"
buildMonth 2010  8 = monthHelper "Schmalz's First Prize Beer" "http://kol.coldfront.net/thekolwiki/index.php/Schmalz%27s_First_Prize_Beer"
buildMonth 2010  9 = monthHelper "Greatest American Pants" "http://kol.coldfront.net/thekolwiki/index.php/Greatest_American_Pants"
buildMonth 2010 10 = monthHelper "organ grinder" "http://kol.coldfront.net/thekolwiki/index.php/Organ_grinder"
buildMonth 2010 11 = monthHelper "Grumpy Bumpkin's Pumpkin Seed Catalog" "http://kol.coldfront.net/thekolwiki/index.php/Grumpy_Bumpkin%27s_Pumpkin_Seed_Catalog"
buildMonth 2010 12 = monthHelper "hibernating robot reindeer" "http://kol.coldfront.net/thekolwiki/index.php/Hibernating_robot_reindeer"
buildMonth 2011  1 = monthHelper "Loathing Legion knife" "http://kol.coldfront.net/thekolwiki/index.php/Loathing_Legion_knife"
buildMonth 2011  2 = monthHelper "a cute angel" "http://kol.coldfront.net/thekolwiki/index.php/A_cute_angel"
buildMonth 2011  3 = monthHelper "Sorcerers of the Shore Grimoire" "http://kol.coldfront.net/thekolwiki/index.php/Sorcerers_of_the_Shore_Grimoire"
buildMonth 2011  4 = monthHelper "Clan shower" "http://kol.coldfront.net/thekolwiki/index.php/Clan_shower"
buildMonth 2011  5 = monthHelper "My Own Pen Pal kit" "http://kol.coldfront.net/thekolwiki/index.php/My_Own_Pen_Pal_kit"
buildMonth 2011  6 = monthHelper "mysterious chest" "http://kol.coldfront.net/thekolwiki/index.php/Mysterious_chest"
buildMonth 2011  7 = monthHelper "Operation Patriot Shield" "http://kol.coldfront.net/thekolwiki/index.php/Operation_Patriot_Shield"
buildMonth 2011  8 = monthHelper "fairy-worn boots" "http://kol.coldfront.net/thekolwiki/index.php/Fairy-worn_boots"
buildMonth 2011  9 = monthHelper "Tome of Clip Art" "http://kol.coldfront.net/thekolwiki/index.php/Tome_of_Clip_Art"
buildMonth 2011 10 = monthHelper "Make-Your-Own-Vampire-Fangs kit" "http://kol.coldfront.net/thekolwiki/index.php/Make-Your-Own-Vampire-Fangs_kit"
buildMonth 2011 11 = monthHelper "stuffed-shirt scarecrow" "http://kol.coldfront.net/thekolwiki/index.php/Stuffed-shirt_scarecrow"
buildMonth 2011 12 = monthHelper "Mint Salton Pepper's Peppermint Seed Catalog" "http://kol.coldfront.net/thekolwiki/index.php/Mint_Salton_Pepper%27s_Peppermint_Seed_Catalog"
buildMonth 2012  1 = monthHelper "Libram of Resolutions" "http://kol.coldfront.net/thekolwiki/index.php/Libram_of_Resolutions"
buildMonth 2012  2 = monthHelper "can of Rain-Doh" "http://kol.coldfront.net/thekolwiki/index.php/Can_of_Rain-Doh"
buildMonth 2012  3 = monthHelper "Small Medium" "http://kol.coldfront.net/thekolwiki/index.php/Small_Medium"
buildMonth 2012  4 = monthHelper "Boris's Helm" "http://kol.coldfront.net/thekolwiki/index.php/Boris%27s_Helm"
buildMonth 2012  5 = monthHelper "Olympic-sized Clan crate" "http://kol.coldfront.net/thekolwiki/index.php/Olympic-sized_Clan_crate"
buildMonth 2012  6 = monthHelper "Moping Artistic Goth Kid" "http://kol.coldfront.net/thekolwiki/index.php/Moping_Artistic_Goth_Kid"
buildMonth 2012  7 = monthHelper "Camp Scout backpack" "http://kol.coldfront.net/thekolwiki/index.php/Camp_Scout_backpack"
buildMonth 2012  8 = monthHelper "Unagnimated Gnome" "http://kol.coldfront.net/thekolwiki/index.php/Unagnimated_Gnome"
buildMonth 2012  9 = monthHelper "box of bear arms" "http://kol.coldfront.net/thekolwiki/index.php/Box_of_bear_arms"
buildMonth 2012 10 = monthHelper "Pete & Jackie's Dragon Tooth Emporium Catalog" "http://kol.coldfront.net/thekolwiki/index.php/Pete_%26_Jackie%27s_Dragon_Tooth_Emporium_Catalog"
buildMonth 2012 11 = monthHelper "deactivated nanobots" "http://kol.coldfront.net/thekolwiki/index.php/Deactivated_nanobots"
buildMonth 2012 12 = monthHelper "Thinknerd's Grimoire of Geeky Gifts" "http://kol.coldfront.net/thekolwiki/index.php/Thinknerd%27s_Grimoire_of_Geeky_Gifts"
buildMonth 2013  1 = monthHelper "Snow Suit" "http://kol.coldfront.net/thekolwiki/index.php/Snow_Suit"
buildMonth 2013  2 = monthHelper "GameInformPowerDailyPro subscription card" "http://kol.coldfront.net/thekolwiki/index.php/GameInformPowerDailyPro_subscription_card"
buildMonth 2013  3 = monthHelper "Jarlsberg's pan" "http://kol.coldfront.net/thekolwiki/index.php/Jarlsberg%27s_pan"
buildMonth 2013  4 = monthHelper "Libram of Pulled Taffy" "http://kol.coldfront.net/thekolwiki/index.php/Libram_of_Pulled_Taffy"
buildMonth 2013  5 = monthHelper "Order of the Green Thumb Order Form" "http://kol.coldfront.net/thekolwiki/index.php/Order_of_the_Green_Thumb_Order_Form"
buildMonth 2013  6 = monthHelper "adventurer clone egg" "http://kol.coldfront.net/thekolwiki/index.php/Adventurer_clone_egg"
buildMonth 2013  7 = monthHelper "Clan hot dog stand" "http://kol.coldfront.net/thekolwiki/index.php/Clan_hot_dog_stand"
buildMonth 2013  8 = monthHelper "Folder Holder" "http://kol.coldfront.net/thekolwiki/index.php/Folder_Holder"
buildMonth 2013  9 = monthHelper "KoLHS Pep Squad Box" "http://kol.coldfront.net/thekolwiki/index.php/KoLHS_Pep_Squad_Box"
buildMonth 2013 10 = monthHelper "deanimated reanimator's coffin" "http://kol.coldfront.net/thekolwiki/index.php/Deanimated_reanimator%27s_coffin"
buildMonth 2013 11 = monthHelper "Pantsgiving" "http://kol.coldfront.net/thekolwiki/index.php/Pantsgiving"
buildMonth 2013 12 = monthHelper "The Smith's Tome" "http://kol.coldfront.net/thekolwiki/index.php/The_Smith%27s_Tome"
buildMonth 2014  1 = monthHelper "Discontent™ Winter Garden Catalog" "http://kol.coldfront.net/thekolwiki/index.php/Discontent%E2%84%A2_Winter_Garden_Catalog"
buildMonth 2014  2 = monthHelper "Buddy Bjorn" "http://kol.coldfront.net/thekolwiki/index.php/Buddy_Bjorn"
buildMonth 2014  3 = monthHelper "Sneaky Pete's leather jacket" "http://kol.coldfront.net/thekolwiki/index.php/Sneaky_Pete%27s_leather_jacket"
buildMonth 2014  4 = monthHelper "Little Geneticist DNA-Splicing Lab" "http://kol.coldfront.net/thekolwiki/index.php/Little_Geneticist_DNA-Splicing_Lab"
buildMonth 2014  5 = monthHelper "airplane charter: Spring Break Beach" "http://kol.coldfront.net/thekolwiki/index.php/Airplane_charter:_Spring_Break_Beach"
buildMonth 2014  6 = monthHelper "still grill" "http://kol.coldfront.net/thekolwiki/index.php/Still_grill"
buildMonth 2014  7 = monthHelper "Clan speakeasy" "http://kol.coldfront.net/thekolwiki/index.php/Clan_speakeasy"
buildMonth 2014  8 = monthHelper "The Confiscator's Grimoire" "http://kol.coldfront.net/thekolwiki/index.php/The_Confiscator%27s_Grimoire"
buildMonth 2014  9 = monthHelper "Thor's Pliers" "http://kol.coldfront.net/thekolwiki/index.php/Thor%27s_Pliers"
buildMonth 2014 10 = monthHelper "airplane charter: Conspiracy Island" "http://kol.coldfront.net/thekolwiki/index.php/Airplane_charter:_Conspiracy_Island"
buildMonth 2014 11 = monthHelper "fist turkey outline" "http://kol.coldfront.net/thekolwiki/index.php/Fist_turkey_outline"
buildMonth 2014 12 = monthHelper "Crimbo sapling" "http://kol.coldfront.net/thekolwiki/index.php/Crimbo_sapling"
buildMonth 2015  1 = monthHelper "Chateau Mantegna room key" "http://kol.coldfront.net/thekolwiki/index.php/Chateau_Mantegna_room_key"
buildMonth 2015  2 = monthHelper "bottle of lovebug pheromones" "http://kol.coldfront.net/thekolwiki/index.php/Bottle_of_lovebug_pheromones"
buildMonth 2015  3 = monthHelper "Ed the Undying exhibit crate" "http://kol.coldfront.net/thekolwiki/index.php/Ed_the_Undying_exhibit_crate"
buildMonth 2015  4 = monthHelper "airplane charter: Dinseylandfill" "http://kol.coldfront.net/thekolwiki/index.php/Airplane_charter:_Dinseylandfill"
buildMonth 2015  5 = monthHelper "portable Mayo Clinic" "http://kol.coldfront.net/thekolwiki/index.php/Portable_Mayo_Clinic"
buildMonth 2015  6 = monthHelper "yellow puck" "http://kol.coldfront.net/thekolwiki/index.php/Yellow_puck"
buildMonth 2015  7 = monthHelper "Pack of Every Card" "http://kol.coldfront.net/thekolwiki/index.php/Pack_of_Every_Card"
buildMonth 2015  8 = monthHelper "airplane charter: That 70s Volcano" "http://kol.coldfront.net/thekolwiki/index.php/Airplane_charter:_That_70s_Volcano"
buildMonth 2015  9 = monthHelper "shrine to the Barrel god" "http://kol.coldfront.net/thekolwiki/index.php/Shrine_to_the_Barrel_god"
buildMonth 2015 10 = monthHelper "haunted doghouse" "http://kol.coldfront.net/thekolwiki/index.php/Haunted_doghouse"
buildMonth 2015 11 = monthHelper "airplane charter: The Glaciest" "http://kol.coldfront.net/thekolwiki/index.php/Airplane_charter:_The_Glaciest"
buildMonth 2015 12 = monthHelper "machine elf capsule" "http://kol.coldfront.net/thekolwiki/index.php/Machine_elf_capsule"
buildMonth 2016  1 = monthHelper "X-32-F snowman crate" "http://kol.coldfront.net/thekolwiki/index.php/X-32-F_snowman_crate"
buildMonth 2016  2 = monthHelper "LT&T telegraph office deed" "http://kol.coldfront.net/thekolwiki/index.php/LT%26T_telegraph_office_deed"
buildMonth 2016  3 = monthHelper "Witchess Set" "http://kol.coldfront.net/thekolwiki/index.php/Witchess_Set"
buildMonth 2016  4 = monthHelper "Clan Floundry" "http://kol.coldfront.net/thekolwiki/index.php/Clan_Floundry"
buildMonth 2016  5 = monthHelper "disconnected intergnat" "http://kol.coldfront.net/thekolwiki/index.php/Disconnected_intergnat"
buildMonth 2016  6 = monthHelper "Source Terminal" "http://kol.coldfront.net/thekolwiki/index.php/Source_terminal"
buildMonth 2016  7 = monthHelper "detective school application" "http://kol.coldfront.net/thekolwiki/index.php/Detective_school_application"
buildMonth 2016  8 = monthHelper "DIY protonic accelerator kit" "http://kol.coldfront.net/thekolwiki/index.php/DIY_protonic_accelerator_kit"
buildMonth 2016  9 = monthHelper "Dear Past Self Package" "http://kol.coldfront.net/thekolwiki/index.php/Dear_Past_Self_Package"
buildMonth 2016 10 = monthHelper "li'l orphan tot" "http://kol.coldfront.net/thekolwiki/index.php/Li%27l_orphan_tot"
buildMonth 2016 11 = monthHelper "Granny Tood's Thanksgarden Catalog" "http://kol.coldfront.net/thekolwiki/index.php/Granny_Tood%27s_Thanksgarden_Catalog"
buildMonth 2016 12 = monthHelper "Build-a-City Gingerbread Kit" "http://kol.coldfront.net/thekolwiki/index.php/Build-a-City_Gingerbread_kit"
buildMonth 2017  1 = monthHelper "space planula" "http://kol.coldfront.net/thekolwiki/index.php/Space_planula"
buildMonth 2017  2 = monthHelper "heart-shaped crate" "http://kol.coldfront.net/thekolwiki/index.php/Heart-shaped_crate"
buildMonth 2017  3 = monthHelper "unpowered Robortender" "http://kol.coldfront.net/thekolwiki/index.php/Unpowered_Robortender"
buildMonth 2017  4 = monthHelper "Spacegate access badge" "http://kol.coldfront.net/thekolwiki/index.php/Spacegate_access_badge"
buildMonth 2017  5 = monthHelper "New-You Club Membership Form" "http://kol.coldfront.net/thekolwiki/index.php/New-You_Club_Membership_Form"
buildMonth 2017  6 = monthHelper "suspicious package" "http://kol.coldfront.net/thekolwiki/index.php/Suspicious_package"
buildMonth 2017  7 = monthHelper "LI-11 Motor Pool voucher" "http://kol.coldfront.net/thekolwiki/index.php/LI-11_Motor_Pool_voucher"
buildMonth 2017  8 = monthHelper "Pocket Meteor Guide" "http://kol.coldfront.net/thekolwiki/index.php/Pocket_Meteor_Guide"
buildMonth 2017  9 = monthHelper "corked genie bottle" "http://kol.coldfront.net/thekolwiki/index.php/Corked_genie_bottle"
buildMonth 2017 10 = monthHelper "xo-skeleton-in-a-box" "http://kol.coldfront.net/thekolwiki/index.php/Xo-skeleton-in-a-box"
buildMonth 2017 11 = monthHelper "pantogram" "http://kol.coldfront.net/thekolwiki/index.php/Pantogram"
buildMonth 2017 12 = monthHelper "locked mumming trunk" "http://kol.coldfront.net/thekolwiki/index.php/Locked_mumming_trunk"
buildMonth 2018  1 = monthHelper "January's Garbage Tote (unopened)" "http://kol.coldfront.net/thekolwiki/index.php/January%27s_Garbage_Tote_(unopened)"
buildMonth 2018  2 = monthHelper "Clan Carnival Game" "http://kol.coldfront.net/thekolwiki/index.php/Clan_Carnival_Game"
buildMonth 2018  3 = monthHelper "Pokéfam Guide to Capturing All of Them" "http://kol.coldfront.net/thekolwiki/index.php/Pok%C3%A9fam_Guide_to_Capturing_All_of_Them"
buildMonth 2018  4 = monthHelper "FantasyRealm membership packet" "http://kol.coldfront.net/thekolwiki/index.php/FantasyRealm_membership_packet"
buildMonth 2018  5 = monthHelper "God Lobster Egg" "http://kol.coldfront.net/thekolwiki/index.php/God_Lobster_Egg"
buildMonth 2018  6 = monthHelper "SongBoom™ BoomBox Box" "http://kol.coldfront.net/thekolwiki/index.php/SongBoom%E2%84%A2_BoomBox_Box"
buildMonth 2018  7 = monthHelper "kitten burglar" "http://kol.coldfront.net/thekolwiki/index.php/Kitten_burglar"
buildMonth 2018  8 = monthHelper "Bastille Battalion control rig crate" "http://kol.coldfront.net/thekolwiki/index.php/Bastille_Battalion_control_rig_crate"
buildMonth 2018  9 = monthHelper "Neverending Party invitation envelope" "http://kol.coldfront.net/thekolwiki/index.php/Neverending_Party_invitation_envelope"
buildMonth 2018 10 = monthHelper "latte lovers club card" "http://kol.coldfront.net/thekolwiki/index.php/Latte_lovers_club_card"
buildMonth 2018 11 = monthHelper "voter registration form" "http://kol.coldfront.net/thekolwiki/index.php/Voter_registration_form"
buildMonth 2018 12 = monthHelper "Boxing Day care pass" "http://kol.coldfront.net/thekolwiki/index.php/Boxing_Day_care_package"
buildMonth 2019  1 = monthHelper "Kramco Industries packing carton" "http://kol.coldfront.net/thekolwiki/index.php/Kramco_Industries_packing_carton"
buildMonth _ _ = const "<td></td>"
